### ISSUE TITLE
Blacklist Erebus Offering Altar in CarryOn

### ISSUE THREAD

**Issue by FriedEgg** [BedrockLegends/Journey-Across-The-Void#11]
Issue description:

To pickup the Gaean Gem from the Offering Altar you need to Shift+Right Click.  Instead of retrieving the gem though, you pick up the altar.  Adding erebus:altar_offering to the Carry On Configuration Blacklist (Blocks that the Player cannot pick up) list allowed me to retrieve the gem.
  
Steps to reproduce:
1. Place Offering Altar
2. Craft Gaean Gem
3. Shift+Right Click Altar

Forge Version: 14.23.5.2854
Server Version: 1.12.2
Modpack Version: 13.4

**Comment by FriedEgg** [comment]
erebus:gaean_keystone also has the same issue when trying to retrieve Staff of Gaea

**Comment by BedrockLegends** [comment]
Wont be fixed for like another week or two as people are getting annoyed with the many updates
