### ISSUE TITLE
Crash during loading

### ISSUE THREAD

**Issue by chemban** [BedrockLegends/Journey-Across-The-Void#14]
Issue description:

 game crashes before it finishes loading.  This usually occurs after an in game crash and may persist between 1-3 times before game will start again.

 
Steps to reproduce:
1.start the game.
2.
3.

 
Version (make sure you are on the latest version before reporting, Do not put latest or last updated):

Forge Version: 14.23.5.2854

Server Version:

Modpack Version: 13.6

 
If a  Crash log is relevant for this issue, link it here using one of the sites below.)
Do not post your crash log without using one of the sites below.

 

Gist: https://gist.github.com/

Pastebin:  https://pastebin.com/MZpzveq8

Hastebin: https://hastebin.com/

**Comment by BedrockLegends** [comment]
It looks to be an issue with Java, but I will have @MasterSloth1 check it out when he wakes up

**Comment by chemban** [comment]
I just wanted to add that the crash I am getting is from an "already building vertices" error.  I tried to remove journey maps to test if that was the issue but the pack refused to load without the mod.  Would you like a crash log and separate report or do you think this is part of the same issue?

**Comment by BedrockLegends** [comment]
Id say try reinstalling the pack, I have not had any issues with loading the pack. It could be bad install or a launcher issue .
