### ISSUE TITLE
Crash - Ticking player

### ISSUE THREAD

**Issue by matthewdavis** [BedrockLegends/Journey-Across-The-Void#15]
Issue description:

I looked away and my game crashed. I was working on getting my simple network setup. 

 
Steps to reproduce:
1. Unknown.

 
Version (make sure you are on the latest version before reporting, Do not put latest or last updated):
1.12.2

Forge Version:
14.23.5.2854

Server Version:

Modpack Version:
13.6
 
Crash Log:

https://gist.github.com/matthewdavis/bef06113c0040ef68f0f75e64ec5f7e5

**Comment by BedrockLegends** [comment]
No clue, its some sort of galacticraft issue and if we revert our version we might break alot of stuff

**Comment by matthewdavis** [comment]
Ok. No worries. Closing.
