### ISSUE TITLE
Payload may not be larger than 32767 bytes

### ISSUE THREAD

**Issue by LarcekGiglamesh** [BedrockLegends/Journey-Across-The-Void#16]
Issue description:
Using JEI to fill even very easy recipes into AE2 Crafting Table crashes. 
Reproducable in SP, Achievable Setup, Backup Energy, No Inventory, Only Essential Materials in Storage
 
 
Steps to reproduce:
1. Singleplayer
2. Creative (for quick setup)
3. Achievable Stable Power Source (and Backups)
4. 64k Disk (dropping from Sieving as well)
5. Minimal Setup (see Screenshots)
6. One Steack of Each: Wood, Planks, Sticks
7. Trying to Auto Fill from JEI: "@actually crate"
8.1 Multiplayer: Crash & Disconnect
8.2 Singleplayer: Shutting Down or Perma Freeze

Modpack Version: 13.6
 
Crash Error:
https://gist.github.com/LarcekGiglamesh/56cf3047299f4033c74c296e6f1f515a

![2020-05-14_00 23 14](https://user-images.githubusercontent.com/19149222/81872531-2fe05080-957a-11ea-86a1-f8e9a4c163c3.png)
![2020-05-14_00 23 16](https://user-images.githubusercontent.com/19149222/81872532-31117d80-957a-11ea-94f3-cf7ebf590cd6.png)
![2020-05-14_00 23 18](https://user-images.githubusercontent.com/19149222/81872533-31aa1400-957a-11ea-99da-59b68eb0f4b3.png)
![2020-05-14_00 23 32](https://user-images.githubusercontent.com/19149222/81872539-32db4100-957a-11ea-9f01-998cf1dacfb5.png)
![2020-05-14_00 23 35](https://user-images.githubusercontent.com/19149222/81872540-32db4100-957a-11ea-9887-266aaede4990.png)

When Clicking that [+] we Crash.

**Comment by Warbringer12** [comment]
can you also post your lastest log too that would be helpful also

**Comment by BedrockLegends** [comment]
@LarcekGiglamesh Looking to the ae2 thing now

**Comment by LarcekGiglamesh** [comment]
my bad, had to recreate the setup since the original world didnt load and required a kill task so it took a while.

[latest.log](https://github.com/BedrockLegends/Journey-Across-The-Void/files/4625153/latest.log)

additional feedback:
not all recipes crashes, actually additions is just one of the easier ones with no big data attached that crashed, so it threw me off. many, even modded, recipes work just fine.

**Comment by BedrockLegends** [comment]
Well I just fixed the broken ae2 config

**Comment by LarcekGiglamesh** [comment]
Modpack Version: 13.7 on a fresh profile
Tested in: Singleplayer Creative, Void World Type
Description: Still Same Issue as before

![2020-05-19_19 17 51](https://user-images.githubusercontent.com/19149222/82357723-c8a51f00-9a05-11ea-9899-6ee39be43890.png)
[latest.log](https://github.com/BedrockLegends/Journey-Across-The-Void/files/4652143/latest.log)
