### ISSUE TITLE
Agricraft Crash

### ISSUE THREAD

**Issue by mcoffma1** [BedrockLegends/Journey-Across-The-Void#20]
Issue description: 
Sometimes, when I enter an inventory that shows JEI, the game will freeze and quickly crash after.
Looking at the crash report, it looks like it's due to a rendering error with Agricraft Water Irrigation Channels. Removing Agricraft fixes it entirely but, I'd rather have the mods you intended in the pack.
NOTE: Line 100 states the suspected mod is Agricraft

 
Steps to reproduce:
1. Press 'E' to access inventory or access another inventory/storage
2. Search for anything 'water' related.
3. ???
NOTE: It doesn't happen all the time, seems random.

 
Version (make sure you are on the latest version before reporting, Do not put latest or last updated):
1.12

Forge Version:
1.12

Server Version:
Local

Modpack Version:
13.7

 
If a  Crash log is relevant for this issue, link it here using one of the sites below.)
Do not post your crash log without using one of the sites below.

https://pastebin.com/aUEATpAx

**Comment by BedrockLegends** [comment]
We cant fix this as it seems this mod is not being worked on and I would not even know where to look
