### ISSUE TITLE
Mob kill quest line resets

### ISSUE THREAD

**Issue by Aironax** [BedrockLegends/Journey-Across-The-Void#21]
Issue description:
When completeing the mob killing tasks/ quest you can hand the quest in but then it just resets like it was never done but the overall quest chapter % complete still increases, this makes it hard to track what has and has not been completed
 

 
Steps to reproduce:
1. Complete quest (Kill the mobs)
2. Hand in/ Complete quest
3. Quest resets like it was never handed in, this was not a issue prior to 13.7

 
Version (make sure you are on the latest version before reporting, Do not put latest or last updated):

13.7 loaded as the "release" on the twitch launch

**Comment by BedrockLegends** [comment]
NOT A BUG, Lect did changes to the quest book and might of cause it to reset

**Comment by Aironax** [comment]
it resets every time i complete it, so is it a repeatable quest and how does one track progress of what has or has not been finished?
