### ISSUE TITLE
Correct Mod Version

### ISSUE THREAD

**Issue by ash120903** [BedrockLegends/Journey-Across-The-Void#22]
Hello, I've had this issue a couple of times and I'm so sorry to say I need the correct versions for Micdoodle core, Galacticraft planets and core, please. again I'm sorry I am unsure why this keeps happening.

**Comment by lectavison** [comment]
sorry this is a issue that sometimes happens with some launchers where they forget to remove the old versions of the mods, a general rule is that the version with the newer date modified or with a higher version number in the name of the mod file is the correct version. the correct versions for JATV 13.7 is GalacticraftCore-1.12.2-4.0.2.272.jar, Galacticraft-Planets-1.12.2-4.0.2.272.jar, and MicdoodleCore-1.12.2-4.0.2.272.jar.
