### ISSUE TITLE
Some bugs/requests

### ISSUE THREAD

**Issue by Pxulooo** [BedrockLegends/Journey-Across-The-Void#23]
Issue description:

there's every seed ans sapling in the market but not Tomatillo and Juniperberry, there's no other way to obtain them so can't finis the food quest line 

-------------------

Another bug with Mekanism : not detecting the basic combining factory, crated it 3 times  dropped and get back and not detecting
 
-------------------

Another one with the attractor obelisk of Ender IO, needs a soul vial with Villager but in the pack there's only Nibiru Villager and Abyssal Villager

-------------------

Again with Villagers, need a trade for the Arc Furnace Electrodes with Imerssive Engineering blueprint, but where to find the villager ?

-------------------

In the PSI quest line, the quest n°10 need a focusing rod but not detecting

 
Version (make sure you are on the latest version before reporting, Do not put latest or last updated):

Forge Version:

Server Version: 

Modpack Version: 13.7

 
If a  Crash log is relevant for this issue, link it here using one of the sites below.)
Do not post your crash log without using one of the sites below.

 

Gist: https://gist.github.com/

Pastebin: https://pastebin.com/

Hastebin: https://hastebin.com/

**Comment by lectavison** [comment]
if one type of Market does not work try the other type of market. Also you can get a villager through Botania

**Comment by MasterSloth1** [comment]
![image](https://user-images.githubusercontent.com/34207969/82266628-4cd3b400-99be-11ea-8949-ef671ffa4e7c.png)
![image](https://user-images.githubusercontent.com/34207969/82266666-637a0b00-99be-11ea-80bb-8dab92ead94d.png)
these 2 seeds can be found in the pams harvestcraft market
ive fixed the mekanism machines the nbt data was borked lol
if you make a cocoon of caprice and right click emeralds onto the cocoon it will grow a random villager u can defiantly get minecraft villagers this way
Focusing rod was also borked and is now fixed sorry about that do note that the spell nodes are still broken (and by broken i mean any spell node will complete the spell node quests)

**Comment by Pxulooo** [comment]
thanks for your answer, havent see that there's another market and i didn't
know the villager tip so i'll try it :)

Le mar. 19 mai 2020 à 04:03, MasterSloth1 <notifications@github.com> a
écrit :
