### ISSUE TITLE
Payload may not be larger than 32767 bytes, Continued

### ISSUE THREAD

**Issue by LarcekGiglamesh** [BedrockLegends/Journey-Across-The-Void#25]
**Reference:**
https://github.com/BedrockLegends/Journey-Across-The-Void/issues/16

**Modpack Version:** 
13.7 on a fresh profile

**Tested in:** 
Singleplayer Creative, Void World Type

**Description:** 
• Auto Fill Crashing Clients (eg "@actually crate")
• Still Same Issue as before, potential crash or disconnect, SP world becoming unable to load afterwards
• New Issue since i could not reopen old Issue

![2020-05-19_19 17 51](https://user-images.githubusercontent.com/19149222/82357723-c8a51f00-9a05-11ea-9899-6ee39be43890.png)
[latest.log](https://github.com/BedrockLegends/Journey-Across-The-Void/files/4652143/latest.log)

**Comment by MasterSloth1** [comment]
[https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3820](url)

**Comment by LarcekGiglamesh** [comment]
**Fix Suggestion:** 
Remove Binnie Mods "binnie-mods-1.12.2-2.5.1.203.jar"

**Comments:**
Since minecraft:sticks likely were not at fault, i checked for too much data on wood/planks, so i tried removing Binnie Mods and it worked. Haven't confirmed any other recipe crashing yet though, so there might be more crashing recipes out there.
