### ISSUE TITLE
Chopping Block Quest Only Completed by Oak Chopping Block

### ISSUE THREAD

**Issue by Aragolt** [BedrockLegends/Journey-Across-The-Void#26]
Issue description:
Despite the list showing all valid items for the Chopping Block quest in the main questline, only Oak Chopping Block will complete the quest. This can cause a softlock (without the emergency items) if any of the 5 wood types provided besides Oak is used to craft the chopping block, due to not having planks to make an axe without the quest reward.
 
Steps to reproduce:
1. Unlock the relevant quest (4th in the main quest line)
2. Give yourself or craft any chopping block besides Oak
3. Confirm that the quest does not complete

Version (make sure you are on the latest version before reporting, Do not put latest or last updated): 1.12.2

Forge Version: 14.23.5.2854

Server Version: Local or JATV Public Server

Modpack Version: 13.7

**Comment by lectavison** [comment]
Issue has fixed in the next update and will require you to have a chopping block in your inventory when the pack updates to recomplete the quest.
