### ISSUE TITLE
broken blocks vanishing

### ISSUE THREAD

**Issue by bloodscon** [BedrockLegends/Journey-Across-The-Void#27]
Issue description:

Broken blocks vanishing
 
Steps to reproduce:

1.breaking a block with pick sometimes causes the block to vanish happens more often with the tinks pick then the default pick
 
Version (make sure you are on the latest version before reporting, Do not put latest or last updated):

Version: 13.7

Minecraft Version: 1.12.2

(modded) forge-14.23.5.2854
 
If a  Crash log is relevant for this issue, link it here using one of the sites below.)
Do not post your crash log without using one of the sites below.

 

Gist: https://gist.github.com/

Pastebin: https://pastebin.com/

Hastebin: https://hastebin.com/

**Comment by BedrockLegends** [comment]
Sounds like client side lag or server lag
