### ISSUE TITLE
Fluid Cows Quest have ERROR liquid (probably More Planets fluid)

### ISSUE THREAD

**Issue by progheal** [BedrockLegends/Journey-Across-The-Void#29]
**Issue description:**

Some quest in Fluid Cows section require ERROR liquid. See the attached picture below.
 
Currently known ERRORs and the registry names of the fluid they require according to config files: (coordinate relative to center)
* 2 Right, 1 Down: crystallize_lava_fluid
* 1 Right, 4 Down: crystallize_water_fluid
* 3 Left, 7 Down: cheese_of_milk_fluid
* 9 Right, 9 Down (ie. 3rd row from bottom, 6th from right): purify_water_fluid
* 13 Right, 9 Down (ie. 3rd row from bottom, 2nd from right): cheese_of_milk_gas

These fluids seems all belong to More Planets.

**Steps to reproduce:**
1. Open Quest page and navigate to Fluid Cows section.
2. Navigate to the quests shown below. They will say "Fluid Cow: ERROR".

![](https://i.imgur.com/c7U0ajD.png)

 
**Version:**
Forge Version: 14.23.5.2854
Modpack Version: 13.7

**Comment by lectavison** [comment]
Issue has fixed in the next update.
