### ISSUE TITLE
Draconic Evolution Tablet download failure

### ISSUE THREAD

**Issue by KuroTheGeek** [BedrockLegends/Journey-Across-The-Void#30]
Issue description: The Tablet cant download the json File from brandon3055 website. 

 

 
Steps to reproduce:
1. Open the Draconic Evolution

There Already exist ah Fix. Only inlcude the Mod VanillaFix in the latest version. I must be only in the Client Files. Here the curseforge Link: https://www.curseforge.com/minecraft/mc-mods/vanillafix

**Comment by BedrockLegends** [comment]
@KuroTheGeek we are not adding Vanilla fix in, we know about this issues already and cant add Vanilla fix as it crashes with a few other mods in the pack

**Comment by lectavison** [comment]
From FAQ!!
Q: Can you get X mod added to 1.12.2?
      A: Mod requests for 1.12.2 will be ignored as the 1.12.2 packs are no longer receiving mod requests.

Q: Why is X mod not in the pack?
      A: Probably because there are Pack breaking bugs with said mod
