### ISSUE TITLE
ME Quantum Ring Crafting Conflict

### ISSUE THREAD

**Issue by IPadAddiction** [BedrockLegends/Journey-Across-The-Void#31]
Issue description:
When crafting the Quantum Ring, the modified recipe with the energy cell fails to work properly when any piece of NBT data does not match the specific one called for by the recipe in JEI.
 
Steps to reproduce:
1. Craft new Thermal Expansion basic energy cell.
2. Change NBT data in any way (i.e. add RF, change IO settings, place in any orientation that isn't front-facing south [NBT match to the recipe]).
3. Attempt to use in the AE Quantum Ring recipe.

Version (make sure you are on the latest version before reporting, Do not put latest or last updated):
Forge Version: Whatever the Current JATV 14.0 release is
Server Version: Singleplayer
Modpack Version: 14.0 Release

**Comment by BedrockLegends** [comment]
The Set custom Recipe works fine in 14.0, We did not set the Recipe to use Energy cells with Power/energy in time. We set it up to use a empty cell
