### ISSUE TITLE
String

### ISSUE THREAD

**Issue by Dopiestcow** [BedrockLegends/Journey-Across-The-Void#34]
Issue description:
The 3x3 craft makes silk rather than mesh for the sieve quest
 

 
Steps to reproduce:
1.
2.
3.

 
Version (make sure you are on the latest version before reporting, Do not put latest or last updated):

Forge Version:14.23.5.2854

Server Version:

Modpack Version:14.6

 
If a  Crash log is relevant for this issue, link it here using one of the sites below.)
Do not post your crash log without using one of the sites below.

 

Gist: https://gist.github.com/

Pastebin: https://pastebin.com/

Hastebin: https://hastebin.com/

**Comment by Warbringer12** [comment]
not a bug... use the change recipe button or make a forestry worktable
