### ISSUE TITLE
blacklisted tools

### ISSUE THREAD

**Issue by bloodscon** [BedrockLegends/Journey-Across-The-Void#38]
Was about to post the following and checked past bugs before doing so and i noticed that someone posted about ultmine and tinkers tools breaking and not returning the resources you placed when using hammers might be an idea to change the hammer quest or put a note on the quest to inform people that ultmine is disabled for tinkers hammers due to a bug.

**Issue description:**
Tinkers hammer blacklisted in ftb ultmine yet normal ex nihilo are not I would expect it to be other way as the quests push towards using the tinkers tools
 

 
**Steps to reproduce:**
1.
2.
3.

 
**Version (make sure you are on the latest version before reporting, Do not put latest or last updated):**

Version: 15.1

Minecraft Version: 1.12.2

(modded) forge-14.23.5.2854

**Have you customized any settings in the pack prior to posting your issue, Please type Yes or No below.**
 
No
 
If a  Crash log is relevant for this issue, link it here using one of the sites below.)
Do not post your crash log without using one of the sites below.

 

**Gist:** https://gist.github.com/

**Pastebin:** https://pastebin.com/

**Hastebin:** https://hastebin.com/

**Comment by lectavison** [comment]
there was a known but with FTB ultmine that required they be black listed from the functionality
.
