### ISSUE TITLE
How are the cow quests completed?  (not a bug; request for information)

### ISSUE THREAD

**Issue by Swanne101** [BedrockLegends/Journey-Across-The-Void#39]
**Issue description:**
I'm terribly sorry but I cannot figure out how to turn in the fluid cow quests.  I've completed the main quest in the center of the cow tab; i've tried having the cows in halters, mob imprisonment tools and piggy backpacks.  I've tried buckets and tanks of their respective fluids.  I'm sorry to have to ask such a silly question, but would very much appreciate it if you'd clue me in.

Your time is appreciated.
 
I don't know how to remove the 'bug' label.  I'm sorry.

 
**Steps to reproduce:**
1.
2.
3.

 
**Version (make sure you are on the latest version before reporting, Do not put latest or last updated):**

**Forge Version:**

**Server Version:**

**Modpack Version:**

**Have you customized any settings in the pack prior to posting your issue, Please type Yes or No below.**

 
If a  Crash log is relevant for this issue, link it here using one of the sites below.)
Do not post your crash log without using one of the sites below.

 

**Gist:** https://gist.github.com/

**Pastebin:** https://pastebin.com/

**Hastebin:** https://hastebin.com/

**Comment by lectavison** [comment]
the individual quests require the cow displayer version of the cow. you can read the description of the cow halter to figure out how to get them into a displayer.
