### ISSUE TITLE
Punching Wood Chapter stuck at 97%

### ISSUE THREAD

**Issue by GamerFerLife** [BedrockLegends/Journey-Across-The-Void#40]
**Please do not make issues that ask for server files**

**Issue description:**
I have completed all of the quests in the Punching Wood chapter, but it says it is not completed
 

 
**Steps to reproduce:**
1. Complete all the quests in Punching Wood
2.
3.

 
**Version (make sure you are on the latest version before reporting, Do not put latest or last updated):**

**Forge Version:**
14.23.5.2854

**Server Version:**

**Modpack Version:**
15.1

**Have you customized any settings in the pack prior to posting your issue, Please type Yes or No below.**
No
 
If a  Crash log is relevant for this issue, link it here using one of the sites below.)
Do not post your crash log without using one of the sites below.

 

**Gist:** https://gist.github.com/

**Pastebin:** https://pastebin.com/

**Hastebin:** https://hastebin.com/

**Comment by lectavison** [comment]
There are hidden quests that require advancement in other chapters before they will show up. This should be adjusted in 15.2 version please update or ask your server admin to update.
