### ISSUE TITLE
Ore Excavation is missing

### ISSUE THREAD

**Issue by broxd** [BedrockLegends/Journey-Across-The-Void#41]
**Please do not make issues that ask for server files**

**Issue description:**
As promised in the quest book the mod 'Ore Excavation' is added and can be used. Since on german keyboards the key does not exist as a single-press-button, I want to bind it to another key. But the mod is missing.

 
**Steps to reproduce:**
1. Start thr game in a new world
2. Open the quest book
3. Finish the first quest ('Disclaimer') and go to the next quest on the right
![2020-07-14_18 09 55](https://user-images.githubusercontent.com/68291873/87449352-60d21580-c5fd-11ea-993f-e9f96d5929b8.png)
4. Search for mod in 'Controls'
![2020-07-14_18 11 56](https://user-images.githubusercontent.com/68291873/87449614-b27aa000-c5fd-11ea-8979-3e079d1f4f8f.png)
5. Search for mod in main menu
![2020-07-14_18 12 40](https://user-images.githubusercontent.com/68291873/87449655-bf978f00-c5fd-11ea-89fd-b363ae3f3940.png)

 
**Version (make sure you are on the latest version before reporting, Do not put latest or last updated):**

**Forge Version:**
forge-14.23.5.2854

**Server Version:**

**Modpack Version:**
15.7

**Have you customized any settings in the pack prior to posting your issue, Please type Yes or No below.**
No
 
If a  Crash log is relevant for this issue, link it here using one of the sites below.)
Do not post your crash log without using one of the sites below.

 

**Gist:** https://gist.github.com/

**Pastebin:** https://pastebin.com/

**Hastebin:** https://hastebin.com/

**Comment by Warbringer12** [comment]
not a bug its called ultimine look that up..

**Comment by broxd** [comment]
Ah, I see. Thanks for your help and sorry for bothering. :)
