### ISSUE TITLE
Issues with world gen

### ISSUE THREAD

**Issue by TheBeeCreator** [BedrockLegends/Journey-Across-The-Void#42]
**Please do not make issues that ask for server files**

**Issue description:**
Generating world on server is not generating a void world and instead acts as if it is generating via default level/world type
 

 
**Steps to reproduce:**
1. Install modpack via creeperhost
2. Start server with level-type:voidworld
3.

 
**Version (make sure you are on the latest version before reporting, Do not put latest or last updated):**

**Forge Version:**
1.12.2-14.23.5.2854

**Server Version:**

**Modpack Version:**
15.7

**Have you customized any settings in the pack prior to posting your issue, Please type Yes or No below.**
No
 
If a  Crash log is relevant for this issue, link it here using one of the sites below.)
Do not post your crash log without using one of the sites below.

 

**Gist:** https://gist.github.com/

**Pastebin:** https://pastebin.com/

**Hastebin:** https://hastebin.com/

**Comment by BedrockLegends** [comment]
Your not using level-type=void

**Comment by TheBeeCreator** [comment]
Ahhhh, it is working fine now. Thank you
