### ISSUE TITLE
Game won't start

### ISSUE THREAD

**Issue by zLc362** [BedrockLegends/Journey-Across-The-Void#44]
**Please do not make issues that ask for server files**

**Issue description:**

 Game won't start after updating it, it starts in the background but it just sits there when i look at it with task manager ,there's no CPU activity and the RAM is a constant number. I have to close it with task manager.

 
**Steps to reproduce:**
1.Start the game
2.Nothing happens
3.Minecraft is running in task manager but not on the screen

 
**Version (make sure you are on the latest version before reporting, Do not put latest or last updated):**

**Forge Version:** 14.23.5.2854

**Server Version:**

**Modpack Version:** 17.2

**Have you customized any settings in the pack prior to posting your issue, Please type Yes or No below.**

 I've turned VSync off

If a  Crash log is relevant for this issue, link it here using one of the sites below.)
Do not post your crash log without using one of the sites below.

 https://pastebin.com/r2f6xZtH

**Gist:** https://gist.github.com/

**Pastebin:** https://pastebin.com/

**Hastebin:** https://hastebin.com/

**Comment by BedrockLegends** [comment]
Say try restarting the game, We have had no issues like this

**Comment by BedrockLegends** [comment]
Its most likely a Twitch/curse issues as they been having major client and website issues for weeks now
