### ISSUE TITLE
Crash in crafting grid

### ISSUE THREAD

**Issue by fowlerhk** [BedrockLegends/Journey-Across-The-Void#45]
**Issue description:**
I have now had 4 crashes while in a crafting grid (immediately after typing the first letter of an item search). The crash has happened with a tinkers crafting station and AE2 crafting terminal. Crashed in my SP world and also after I transferred my save to a local MP server. Does not happen often. I've been playing this pack for only 3 days in total (active and afk) so far though.
 
Note: No idea if this is relevant or useful, but the crash dump mentions rendering agricraft wooden water tank. I reloaded the pack and was able to search for and see the water tanks in JEI.
 
**Steps to reproduce:**
1. Open crafting grid
2. Start typing a search string
3. Occasionally it will crash

 
**Version (make sure you are on the latest version before reporting, Do not put latest or last updated):**

**Forge Version:**   14.23.5.2854

**Server Version:**

**Modpack Version:**   17.2 (I also saw this same crash on 16.9)

**Have you customized any settings in the pack prior to posting your issue, Please type Yes or No below.**
No

 
If a  Crash log is relevant for this issue, link it here using one of the sites below.)
https://gist.github.com/fowlerhk/a7776bef2bd20bfead3c303cb6c41c96

**Comment by lectavison** [comment]
Just searching in JEI without being in a crafting grid will also cause this issue.

**Comment by 73Salmin** [comment]
This bug happens to me very frequently and I am in version 17.9.
