### ISSUE TITLE
were is the ore excavator

### ISSUE THREAD

**Issue by jovi131** [BedrockLegends/Journey-Across-The-Void#48]
**Please do not make issues that ask for server files**

**Issue description:**
there is no ore  excavator mod in the pack pls fix that
 

 
**Steps to reproduce:**
1.download JATV 
2.go to the mods list and there is no mod called Ore Excavation mod

 
**Version (make sure you are on the latest version before reporting, Do not put latest or last updated):**

**Forge Version:**
 forge-14.23.5.2854

**Server Version:**
-----

**Modpack Version:**

Version: 17.5

**Have you customized any settings in the pack prior to posting your issue, Please type Yes or No below.**
no
 
If a  Crash log is relevant for this issue, link it here using one of the sites below.)
Do not post your crash log without using one of the sites below.

 

**Gist:** https://gist.github.com/

**Pastebin:** https://pastebin.com/

**Hastebin:** https://hastebin.com/

**Comment by warpath1985** [comment]
there is in controls search ftb

**Comment by jovi131** [comment]
THX
