### ISSUE TITLE
Enormous amounts of skulls/heads

### ISSUE THREAD

**Issue by persath** [BedrockLegends/Journey-Across-The-Void#49]
Since last version, my mob crusher with a fortune addon card, enchanted with fortune II, gives ungodly amounts of skulls/heads from skelletons, zombies and creepers. I only did a small test and in about 1 minute i got 300+ creeper heads.

**Comment by lectavison** [comment]
I will take a look into it tonight, can you tell me any more details on what mods you are using to kill mobs so I have an Idea where I need to start my investigation?

**Comment by lectavison** [comment]
did some testing and it looks like any block that fakes a player kill on a mob is dropping 50 skulls

**Comment by lectavison** [comment]
we are now waiting on ENDER IO to respond and fix there   ##bug.https://github.com/SleepyTrousers/EnderIO/issues/5440

**Comment by tyler489** [comment]
This is definitly Enderio's Fault Sorry. Henry implemented a new system and forgot to divide the drop rate by 1000

**Comment by lectavison** [comment]
ya i figured it was something like that or they tried to divide by 0.
