### ISSUE TITLE
Discord links invalid

### ISSUE THREAD

**Issue by TeksuneStudio** [BedrockLegends/Journey-Across-The-Void#50]
The Discord links in game (and on the Twitch launcher) are invite-invalid

No crash logs available for this issue.
I can provide a screenshot of the invalid invite if you'd like.

**Comment by warpath1985** [comment]
i use OptiFine_1.12.2_HD_U_F5 had no issues

**Comment by TeksuneStudio** [comment]
> i use OptiFine_1.12.2_HD_U_F5 had no issues

Issue that was present was with OptiFine, AgriCraft textures would disappear. This however is a known issue with AgriCraft and OptiFine and is not something that BedrockLegends would have to worry about or support.

**Comment by lectavison** [comment]
The issue is planned to be fixed when enough mods have updated to justify an update.
