### ISSUE TITLE
Aluminum wire crash

### ISSUE THREAD

**Issue by GetThisHub2** [BedrockLegends/Journey-Across-The-Void#51]
**Please do not make issues that ask for server files**

**Issue description:**
I was trying to make A aluminum wire to use for power for one of my circuit fabricators, when I placed it down it made my game crash, Fortunately I was playing with someone else so I asked them to go over there when their  game crashed
and closed. Mine however just made me leave, not crash and close.
 

 
**Steps to reproduce:**
1. Craft a aluminum wire.
2. Put it in your hotbar.
3. Place it down and crash!

 
**Version (make sure you are on the latest version before reporting, Do not put latest or last updated):**
Version: 17.9 Final
**Forge Version:**
(modded) forge-14.23.5.2854

**Server Version:**
1.12.2

**Modpack Version:**
1.12.2

**Have you customized any settings in the pack prior to posting your issue, Please type Yes or No below.**
No.
 
If a  Crash log is relevant for this issue, link it here using one of the sites below.)
Do not post your crash log without using one of the sites below.

 

**Gist:** https://gist.github.com/

**Pastebin:** https://pastebin.com/

**Hastebin:** https://hastebin.com/

**Comment by lectavison** [comment]
this is a known issue if you are playing in single player then you will have to load your world into a server to get access to the console before anyone logs into the render distance of the aluminum wire. if you are on a server one of the staff members with access to the console should be able to run the "/cofh clearblocks <xStart> <yStart> <zStart> <xEnd> <yEnd> <zEnd> <block>" command to try and remove the block.

**Comment by BedrockLegends** [comment]
Fixed in Final Version 18.0 here, https://www.curseforge.com/minecraft/modpacks/journey-across-the-void/files/3116477

**Comment by GetThisHub2** [comment]
Thank you for fixing this issue!
