### ISSUE TITLE
Focusing rod quest not completing (17.9 Final)

### ISSUE THREAD

**Issue by Noob342** [BedrockLegends/Journey-Across-The-Void#53]
After doing the quests: "Psimetal Rod Frame" , "Quick Rod Crux" , "Sparkling Rod Source" and "Flashing Rod Notch" i made the Focusing Rod using those materials and the quest didn't complete.

the solutions i tried were:
1. making another one using the same materials (just to be sure)
2. throwing it on the ground and picking it back up (this helped in past modpacks with quests)
3. making a focusing rod only using the Psimetal Rod Frame
4. started a Single player world did the quests in creative (including giving me a Focusing Rod from the creative menu)

5. ran the command /ftbquests editing_mode and found the quest has NBT mode on "contain" and the previous 2 Rod quests had it on "ignore"

Packversion: 17.9 Final

**Comment by MasterSloth1** [comment]
Thanks but u fortunately this pack is now discontinued if we ever update I will fix it then but untill then it won't be you will just have to manually complete it

**Comment by BedrockLegends** [comment]
We are focusing on JATV2 for 1.16+
