### ISSUE TITLE
The game version 18.1, 18.2, 18.3 and 18.4 crash on launch.

### ISSUE THREAD

**Issue by 73Salmin** [BedrockLegends/Journey-Across-The-Void#54]
for the modpack version 18.1+ the game will crash on launch saying 
"Unexpected issue occurred and the game has crashed. We are sorry for the inconvenience." then "exit code: 0"
and I don't know how its occurring but when I downdate the game to 18.0 the game launched.

**Comment by lectavison** [comment]
you able to provide any further logs so that we can take a look into more details.

**Comment by 73Salmin** [comment]
its doesnt give me any crash report or anything just that message

**Comment by lectavison** [comment]
What launcher and version of java are you using?

**Comment by shortybsd** [comment]
Please provide the log files to help track the error, if a crashlog doesn't get generated.

**Comment by 73Salmin** [comment]
Now I understood what you mean give me 1 min

**Comment by 73Salmin** [comment]
https://pastebin.pl/view/fe30a5ac

**Comment by lectavison** [comment]
per that log file looks like your copy of the pack has two versions of ThaumicAugmentation, please remove \Mods\ThaumicAugmentation-1.12.2-2.0.9.jar and then try relaunching the newer version of the pack

**Comment by 73Salmin** [comment]
from what you said. after double checking my mods folder there were about 10 duplicated mods.

**Comment by lectavison** [comment]
It looks like the Curseforge launcher goofed when you updated and did not remove all the old mods which it does during the update.
