### ISSUE TITLE
No recipe for nuclearcraft zircaloy

### ISSUE THREAD

**Issue by MaxBellc** [BedrockLegends/Journey-Across-The-Void#7]
Issue description:

 Unable to to craft zircaloy from nuclearcraft. Zircaloy is used to craft molten salt fission vessel, which is part of nuclearcraft molten salt reactor. 

Steps to reproduce:

1.open modpack
2.check recipe for zircaloy in jei

Modpack Version: 12.1

**Comment by BedrockLegends** [comment]
Fixed
